### ISSUE TITLE
Links to non-existing images are created

### ISSUE THREAD

**Issue by simo78** [webnoetic/prettygallery#1]
I have a gallery of 3 images on my web site. Wordpress default gallery shows them without any issues. However, once prettygallery is installed, thumbnails are still displayed properly, but 2 of 3 links get corrupted. 

For example, without prettygallery the HTML code contains link to `image.jpg`, which works perfectly. With prettygallery the link turns to `image-1024x767.jpg`, but no such file exists. Therefore the jQuery modal window shows only an error message when trying to view these images.

The full-size image dimensions are indeed 1024x767. However, unlike thumbnail images, the full-size image file name does not contain the dimensions. I have the following images in my uploads/2013/12 directory:

```
image-1067x450.jpg
image-150x150.jpg
image-200x149.jpg
image-300x224.jpg
image-390x261.jpg
image-690x462.jpg
image.jpg
```

I have been regenerating thumbnails with **Regenerate Thumbnails** plugin and scaling full-size images with **Imsanity** plugin. Therefore it is possible that those plugins have corrupted something. But I am first suggesting that this is a bug with **prettygallery** because the issue occurs only when this plugin has been activated.

**Comment by webnoetic7** [comment]
When any image upload in wordpress than wordpress generate three image and Prettygallery calls large size image in href. I think **Regenerate Thumbnails** plugin corrupt  wordpress media centre.

**Comment by simo78** [comment]
It seems the problem is caused by the call to `wp_get_attachment_image_src($id,'large',false)` within prettygallery.php as it results in a filename that does not exist (filename with dimensions). This was probably caused by **Regenerate Thumbnails** but I will verify it.

However, it seems that you are using different code to get image URL, because this problem only occurs when prettygallery is active. Without prettygallery, my galleries are working perfectly.

**Comment by webnoetic7** [comment]
wp_get_attachment_image_src($id,'large',false) is a standard wordpress function to get url of large image. This function return false only when no image exists (means no format of image). In your case one format of image exist (thumbnail) but other format of image (Large or medium) not exist. which is possible only when media centre images corrupted. 
The current version of plugin not handled this condition, that's why you got error when plugin in active state. I will handled this condition in next version

**Comment by simo78** [comment]
Now looking at `wp_postmeta` which contains:

`:5:"large";a:4:{s:4:"file";s:21:"MK227105-1024x682.jpg";s:5:"width";i:1024;s:6:"height";i:682;s:9:"mime-type";s:10:"image/jpeg";}s:`

The mentioned file `MK227105-1024x682.jpg` is what `wp_get_attachment_image_src` returns. The file did exist, but was removed by _Imsanity_ plugin. Closing this issue now - it has nothing to do with _prettygallery_.

Thanks for your help and sorry for false alarm :).
